# Generated by Django 2.2 on 2020-09-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200925_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_attributes', to='product.Product', verbose_name='product'),
        ),
    ]
