# Generated by Django 2.2 on 2020-09-13 17:35

from django.conf import settings
from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='created time')),
                ('uuid', models.UUIDField(unique=True, verbose_name='uuid')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('paid', models.BooleanField(verbose_name='paid')),
                ('user', models.ForeignKey(on_delete=models.SET(payment.models.create_user), related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoice',
            },
        ),
    ]
