# Generated by Django 2.2 on 2020-10-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_basket_invoice'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='basket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='purchase.Basket', verbose_name='basket'),
        ),
    ]
