# Generated by Django 2.2 on 2020-10-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_invoice_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='basket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='purchase.Basket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(auto_created=True, unique=True, verbose_name='uuid'),
        ),
    ]
