# Generated by Django 2.2 on 2020-09-13 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='created time')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='payment.Invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'db_table': 'basket',
            },
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='created time')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantity')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='purchase.Basket', verbose_name='basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'BasketProduct',
                'verbose_name_plural': 'BasketProducts',
                'db_table': 'basket_product',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(related_name='baskets', through='purchase.BasketProduct', to='product.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(purchase.models.create_user), related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
