# Generated by Django 2.2 on 2020-10-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20201002_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='invoice',
        ),
    ]
