# Generated by Django 2.2 on 2020-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200920_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='catattribute',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='is_parent'),
        ),
    ]
