# Generated by Django 2.2 on 2020-10-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_catattribute_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catattribute',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='category',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='is_parent'),
        ),
    ]
